# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# https://symfony.com/doc/current/best_practices.html
---
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
